name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'PR has been open 15 days with no activity. Remove stale label or comment or this will be closed in 15 days'
          close-pr-message: 'Stale PR closed due to no activity for 15 days'
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: 15
          days-before-pr-close: 15
          operations-per-run: 5000
